name: CV Deployment Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        env:
          EMAIL: igormcsouza@gmail.com
          NAME: Igor Souza
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/igormcsouza/curriculum-vitae.git
          npx gh-pages -d build -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
